import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";

export const metadata = {
  title: "Xniop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      
      <body className={inter.className} className="bg-stone-950 text-white">
        <div className="lg:w-[56rem] md:w-[42rem] sm:w-[36rem] w-[32rem] mx-auto">
          <Navbar/>
          {children}
        </div>
      </body>
        
    </html>
  );
}
